version: "3.8"

services:

    web:
        image: node:18
        container_name: "web_since-how"
        working_dir: /home/node/app
        environment:
            - TZ=Europe/Amsterdam
            - NODE_ENV=development
        ports:
            - 80:3000
            - 24678:24678
        volumes:
            - ./web:/home/node/app
        command: npm run dev